[workspace]
members = [
    "fw-core",
    "fw-ctl",
    "fw-user",
]
resolver="3"

[workspace.dependencies]
libc = "0.2.180"
anyhow = "1.0.101"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.49.0", features = ["full"] }
serde_json = "1.0.149"
